# Generated by Django 6.1 on 2026-08-28 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("jobs", "0002_jobqualification"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_value", models.IntegerField()),
                ("meets_requirement", models.BooleanField(editable=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="applications.application",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobs.jobqualification",
                    ),
                ),
            ],
            options={
                "unique_together": {("application", "qualification")},
            },
        ),
    ]
