# Generated by Django 6.1 on 2026-08-28 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("language", "Language"),
                            ("education", "Education"),
                            ("experience", "Experience"),
                            ("age", "Age"),
                            ("certification", "Certification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("min_value", models.IntegerField()),
                ("min_value_label", models.CharField(blank=True, max_length=100)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
    ]
